version: '3.1'

services:
    mongo:
        build: mongo-container
        container_name: 'mongo'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: database
        volumes:
            - ./mongo-volume:/data/db
        ports:
            - 27017:27017
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq-cloud'
        ports:
            - 5672:5672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
